# Site settings
title: killnono's Blog
email: ckcanfly@gmail.com
description: "NONO's BLOG"
baseurl: ""
url: "http://blog.killnono.com"
twitter_username: nonolilith
github_username:  killnono

# Build settings
markdown: redcarpet
permalink: /:year/:month/:title.html
