# Site settings
title: killnono
email: ckcanfly@gmail.com
description: "NONO's BLOGS"
baseurl: ""
url: "http://blog.killnono.com"
twitter_username: nonolilith
github_username:  nonolilith

# Build settings
markdown: redcarpet
permalink: /:year/:month/:title.html
